version: '3.8'

services:
  app:
    build:
      context: ..
      dockerfile: infrastructure/docker/Dockerfile.dev
    volumes:
      - ..:/workspace
    ports:
      - "8000:8000"  # FastAPI
      - "3000:3000"  # React
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@db:5432/mrp_db
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mrp_db
    depends_on:
      - db
    command: bash -c "while sleep 1000; do :; done"
    networks:
      - mrp-network

  db:
    image: postgres:14
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=mrp_db
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mrp-network

networks:
  mrp-network:
    driver: bridge

volumes:
  postgres-data:
